config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users

  resources :friends, path_names: {new: 'new/:user_id' }

  get 'ledgers/initial_balance'
  post 'ledgers/create_initial_balance'
  resources :ledgers, path_names: {new: 'new/:user_id' }

  get 'home/index'

  root to: "ledgers#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ApplicationRecord
  belongs_to :user
  belongs_to :other_user, class_name: 'User', foreign_key: 'other_user_id'

  def get_other_user(user)
    if user == self.other_user
      return self.user
    end
    self.other_user
  end

end

app/models/ledger.rb
class Ledger < ApplicationRecord
  belongs_to :user
  belongs_to :other_user, class_name: 'User', foreign_key: 'other_user_id', optional: true

  validates :balance, numericality: {greater_than_or_equal_to: 0}
  validates :amount, numericality: {other_than: 0}
  validate :check_users_not_same

  def check_users_not_same
    errors.add(:other_user_id, "users in transaction cannot be the same") if user == other_user
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :ledgers
  has_many :friends

  def lacks_initial_balance?
    self.ledgers.where(other_user_id: nil).count == 0
  end

  def friends
    Friend.where(user: self).or(Friend.where(other_user:self))
  end

  def confirmed_friends
    self.friends.where.not(confirmed_at: nil)
  end

  def friend_status(user)
    friend = Friend.where(user: self, other_user: user).take

    if friend.blank?
      friend = Friend.where(user: user, other_user: self).take
      if friend.blank?
        return nil
      end

      if friend.confirmed_at.blank?
        if friend.rejected_at.blank?
          return :friendship_request_by_self
        end
        return :friendship_rejected_by_other
      end
      return :friend
    end

    if friend.confirmed_at.blank?
      if friend.rejected_at.blank?
        return :friendship_request_by_other
      end
      return :friendship_rejected_by_self
    end

    :friend
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: [:show, :destroy]
  before_action :authenticate_user!

  # GET /friends
  def index
    @friends = current_user.confirmed_friends
  end


  # GET /friends/new
  # this confirms an existing friendship or creates a new request
  # if these were more complex actions I'd split them out in separate functions

  def new
    friend = Friend.where(other_user: current_user, user_id: params[:user_id]).take
    if friend.present?
      friend.confirmed_at = DateTime.now
      friend.save
      redirect_to root_path
      return
    end

    friend = Friend.new

    friend.other_user_id = params[:user_id]
    friend.user = current_user
    friend.save

    redirect_to root_path
  end



  # DELETE /friends/1
  # DELETE /friends/1.json
  def destroy
    @friend.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Friend was successfully removed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
      @friend = nil unless @friend.user == current_user or @friend.other_user == current_user
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:user_id, :other_user_id)
    end
end

app/controllers/ledgers_controller.rb
class LedgersController < ApplicationController
  before_action :set_ledger, only: [:show]
  before_action :authenticate_user!

  # GET /ledgers
  # GET /ledgers.json
  def index
    if current_user.lacks_initial_balance?
      redirect_to '/ledgers/initial_balance'
    end

    @ledgers = Ledger.where(user: current_user).order(id: :desc)
    @users = User.where.not(id: current_user)
    @friends = current_user.confirmed_friends
  end

  # GET /ledgers/1
  # GET /ledgers/1.json
  def show
  end

  # GET /ledgers/new
  def new
    @ledger = Ledger.new
    @ledger.other_user_id = params[:user_id]
  end

  def initial_balance
    @ledger = Ledger.new
  end

  # POST /ledgers
  # POST /ledgers.json
  def create
    @ledger = Ledger.new(ledger_params)

    @ledger.user_id = current_user.id
    @ledger.amount = - @ledger.amount

    last_ledger_balance = Ledger.where(user_id: @ledger.user_id).last.balance
    @ledger.balance = last_ledger_balance + @ledger.amount

    if @ledger.other_user.lacks_initial_balance?
      render :new, locals: {user_id:  @ledger.other_user_id, alert: 'Other user did not complete setup!'}
      return
    end

    @ledger2 = Ledger.new
    @ledger2.amount =  - @ledger.amount
    @ledger2.other_user_id = @ledger.user_id
    @ledger2.user_id = @ledger.other_user_id

    last_ledger_balance = Ledger.where(user_id: @ledger2.user_id).last.balance
    @ledger2.balance = last_ledger_balance + @ledger2.amount

    ActiveRecord::Base.transaction do
      @ledger.save!
      @ledger2.save!

    rescue ActiveRecord::RecordInvalid => e
      render :new, locals: {user_id:  @ledger.other_user_id}
      return
    end

     redirect_to @ledger, notice: 'Transaction was successfully created.'
  end

  def create_initial_balance
    begin
    @ledger = Ledger.new(ledger_params)
    @ledger.user_id = current_user.id
    @ledger.balance = @ledger.amount
    @ledger.save!
    rescue ActiveRecord::RecordInvalid => e
      render :initial_balance, alert:  e
      return
    end

    redirect_to root_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ledger
      @ledger = Ledger.find_by(user: current_user, id: params[:id])
      redirect_to root_path if @ledger.blank?
    end

    # Only allow a list of trusted parameters through.
    def ledger_params
      params.require(:ledger).permit(:other_user_id, :amount)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ledgers_helper.rb
module LedgersHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend, local: true) do |form| %>
  <% if friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :other_user_id %>
    <%= form.number_field :other_user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/friends/_list.html.erb
<br>
<h2>Friends:</h2>
<br>
<% @friends.each do |friend| %>
  <% other_user = friend.get_other_user(current_user) %>
  <%= other_user.email %> <%= link_to 'New Transaction', new_ledger_path(other_user.id) %>
  <%= link_to 'Remove friend', friend, method: :delete, data: { confirm: 'Are you sure?' } %>
  <br>
<% end %>

app/views/friends/index.html.erb
<%= render 'list' %>

app/views/friends/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @friend.user_id %>
</p>

<p>
  <strong>Other user:</strong>
  <%= @friend.other_user_id %>
</p>

<%= link_to 'Back', friends_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Toybank</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/ledgers/_current_balance.html.erb
<h2>Current balance: <%= current_user.ledgers.last.balance %></h2>

app/views/ledgers/_form.html.erb
<%= form_with(model: ledger, local: true) do |form| %>
  <% if ledger.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ledger.errors.count, "error") %> prohibited this ledger from being saved:</h2>

      <ul>
        <% ledger.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    To user:
    <%= ledger.other_user.email %>
    <%= form.hidden_field(:other_user_id, value: ledger.other_user.id) %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.text_field :amount, value: 10 %>
  </div>


  <div class="actions">
    <%= form.submit "Transfer"%>
  </div>
<% end %>

app/views/ledgers/index.html.erb
<p id="notice"><%= notice %></p>
Hello, <%= current_user.email %>

<h1>Transactions</h1>
<%= render 'current_balance' %>
<table>
  <thead>
    <tr>
      <th>Transaction id</th>
      <th>User</th>
      <th>Action</th>
      <th>Amount</th>
      <th>Balance</th>
      <th>Time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ledgers.each do |ledger| %>
      <tr>
        <td><%= ledger.id %></td>
        <td><% if ledger.other_user.present? %> <%= ledger.other_user.email %></td> <% end %>
        <td><% if ledger.amount > 0  %> <span class='received'>Received</span>
          <% else %> <span class='sent'>Sent</span> <% end %></td>
        <td><%= ledger.amount %></td>
        <td><%= ledger.balance %></td>
        <td><%= ledger.created_at %></td>


      </tr>
    <% end %>
  </tbody>
</table>

<%= render 'friends/list' %>
<%= render 'users/list' %>
<br>
<%= link_to('Logout', destroy_user_session_path, method: :delete) %>

app/views/ledgers/initial_balance.html.erb
<h1>Set your initial balance</h1>

<%= form_with(model: @ledger, local: true, url: "/ledgers/create_initial_balance") do |form| %>
  <% if @ledger.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ledger.errors.count, "error") %> prohibited this ledger from being saved:</h2>

      <ul>
        <% @ledger.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= form.label :balance %>
    <%= form.text_field :amount %>
  </div>

  <div class="actions">
    <%= form.submit "Set initial balance" %>
  </div>
<% end %>


<%= link_to 'Back', ledgers_path %>

app/views/ledgers/new.html.erb
<p id="notice"><%= notice %></p>
<p id="error"><%= alert %></p>

<h1>New Transaction</h1>
<%= render 'current_balance' %>


<%= render 'form', ledger: @ledger %>

<%= link_to 'Back', ledgers_path %>

app/views/ledgers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Money sent to User:</strong>
  <%= @ledger.other_user.email %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @ledger.amount %>
</p>

<p>
  <strong>New balance:</strong>
  <%= @ledger.balance %>
</p>

<%= link_to 'Back', ledgers_path %>

app/views/users/_list.html.erb
<br>
<h2>Users:</h2>
<br>
<% @users.each do |user| %>
  <%= user.email %> <%= link_to 'New Transaction', new_ledger_path(user.id) %>
  <% case user.friend_status(current_user)
    when nil%><%= link_to 'Request friendship', new_friend_path(user.id) %>
  <% when :friendship_request_by_self %> Friendship requested
  <% when :friendship_request_by_other %> <%= link_to 'Confirm friend request', new_friend_path(user.id) %>
  <% when :friend %> Friend
  <% end %>
  <br>
<% end %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>